surveys_ssc2016_homepage:
    path: /
    defaults: 
        _controller: SurveysSSC2016Bundle:Survey:index

surveys_ssc2016_form:
    path: /form
    defaults: 
        _controller: SurveysSSC2016Bundle:Survey:form

surveys_ssc2016_submit:
    path: /submit
    defaults: 
        _controller: SurveysSSC2016Bundle:Submit:index

