DROP TABLE IF EXISTS SURVEY_SSC_2016;

CREATE TABLE SURVEY_SSC_2016 (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	it_responsiveness SMALLINT,
	it_courtesy SMALLINT,
	it_solutions SMALLINT,
	it_issuesHandeling SMALLINT,
	it_global SMALLINT,
	it_improve TEXT,
	it_comm SMALLINT,
	it_system SMALLINT,
	it_secu SMALLINT,
	ha_offerCall SMALLINT,
	ha_nego SMALLINT,
	ha_contractFollowUp SMALLINT,
	ha_infoBuying SMALLINT,
	ha_infoSupplier SMALLINT,
	compta_cerAnswer SMALLINT,
	compta_timeAnswer SMALLINT,
	compta_immo SMALLINT,
	compta_rules SMALLINT,
	compta_timeBill SMALLINT,
	compta_receivables SMALLINT,
	compta_who SMALLINT,
	gestion_mission SMALLINT,
	gestion_who SMALLINT,
	gestion_answers SMALLINT,
	gestion_global SMALLINT); 