<?php

namespace Surveys\SSC2016Bundle\Repository;

/**
 * ResultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultsRepository extends \Doctrine\ORM\EntityRepository
{
}
